### ISSUE TITLE
Menu VOD

### ISSUE THREAD

**Issue by stupidhackers** [matthuisman/samsung-tvplus-for-channels#11]
Hi Matts,

there are videos on the Rakuten TV website 

https://www.rakuten.tv/de/gardens/avod-fast

But unfortunately they are not available in your addon under Kodi.

Can you add this to the addon? That VOD is available?

Regards

Admin1

**Comment by matthuisman** [comment]
i dont make a rakuten addon.
Samsung TV addon only.
I have no current plans to add VOD sorry

**Comment by stupidhackers** [comment]
Too bad, I thought you could bring that in. There are lots of free films and series there.
