### ISSUE TITLE
Multiple containers 

### ISSUE THREAD

**Issue by Marryinsam** [matthuisman/samsung-tvplus-for-channels#4]
I have a Pluto container running already in docker and I ran your script to add samsung-tvplus-for-channels. The script ran without error but now docker show it starting consistently. How do I remedy this? 

pi@raspberrypi:~ $ docker ps --format "table {{.ID}}\t{{.Status}}\t{{.Names}}"
CONTAINER ID   STATUS                          NAMES
27dee739bc29   Restarting (1) 20 seconds ago   samsung-tvplus-for-channels
09a0e808bda5   Up 28 minutes                   pluto-for-channels

**Comment by matthuisman** [comment]
use docker logs, you should get an output of what the issue is.
