### ISSUE TITLE
Samsung USA empty / missing

### ISSUE THREAD

**Issue by octavioj** [matthuisman/samsung-tvplus-for-channels#6]
I have loved the container for quite some time but it stopped working for a few weeks. I use watchtower to automatically update containers once a week but I have not seen any updates coming.

Here is my Docker compose:

version: "3.9"
services:
  samsung-tv-channels:
    image: matthuisman/samsung-tvplus-for-channels
    hostname: samsung-tv
    container_name: samsung-tv
    environment:
      - REGION:us
    networks:
      - samsung_tv
    ports:
      - 8182:80
    restart: unless-stopped
networks:
  samsung_tv:
    external: true

I noted explicitly the REGION after the container stopped working.

Going to the address localhost:8182 I can see the links to the M3U and the EPG but visiting the link:

localhost:8182/playlist.m3u

I get the following error:

Error: 'us'

Is this something that others have experienced?

**Comment by octavioj** [comment]
I went to the EPG link

localhost:8182/epg.xml and got the following error:

https://i.mjh.nz/SamsungTVPlus/us.xml returned error 404
Check your REGION is correct

I visited the link:

https://i.mjh.nz/SamsungTVPlus

And noticed US region is no longer showing. It seems that is the reason why the container stopped working.

Any ideas as to what happened?

**Comment by itprotj** [comment]
Chiming in here, whilst I don't specifically use this docker image, I do use the M3U8 files provided through your github repo and also noticed the us.m3u8 and us.xml files disappear.
Not sure if you can but if you change the region to ALL it should work again..

I've at least reverted to using the "all" list in the meantime however I noticed I am now missing at least one channel that I used to have (ChiveTV) not sure if others are missing.

**Comment by matthuisman** [comment]
samsung have switched to a new api endpoint
current one still returns OK data for all countries except US.
So I need to figure out the new endpoints

**Comment by octavioj** [comment]
Thank you for looking into it, Matt.

**Comment by octavioj** [comment]
> Chiming in here, whilst I don't specifically use this docker image, I do use the M3U8 files provided through Matts github repo and also noticed the us.m3u8 and us.xml files disappear. Not sure if you can but if you change the region to ALL it should work again..
> 
> I've at least reverted to using the "all" list in the meantime however I noticed I am now missing at least one channel that I used to have (ChiveTV) not sure if others are missing.

I thought of using all but it seems a bit too long to have. But thank you for the reply.

**Comment by Powerfader1** [comment]
Sorry to bother you, but have you omitted the US groups? In the "all" m3u8 code it loads with a ton but no US. When I try to load the "us" m3u8 code it will not load at all. I am using Tivimate premium on a Nvidia Pro.
Thanks for your time.

https://i.mjh.nz/SamsungTVPlus/us.m3u8

https://i.mjh.nz/SamsungTVPlus/all.m3u8

**Comment by matthuisman** [comment]
please read this issue.

**Comment by matthuisman** [comment]
USA is now back :)

**Comment by octavioj** [comment]
Thank you, Matt!
