### ISSUE TITLE
Stopped updating again

### ISSUE THREAD

**Issue by kamhouse** [matthuisman/samsung-tvplus-for-channels#7]
Seems like the guide data ended a few hours ago and hasn't updated.

**Comment by matthuisman** [comment]
seems ok to me?

**Comment by psperry** [comment]
Seems okay to me too. Only a few hours of guide data but don’t remember what’s normal.

**Comment by matthuisman** [comment]
i suspect there was some bad data that was causing it to fail for a while or just their service was down. let me know if happens again and ill try to look quicker
