### ISSUE TITLE
Guide data not updating

### ISSUE THREAD

**Issue by SethL** [matthuisman/samsung-tvplus-for-channels#8]
My guide data for channels quit updating.  Channels shows in the logs that there are out of date airings.  When I view the epg.xml it confirms this. I compared mine to https://raw.githubusercontent.com/matthuisman/i.mjh.nz/master/SamsungTVPlus/us.xml and it matches exactly.  So something may have barfed again :-(

**Comment by matthuisman** [comment]
looks like its ok now?

**Comment by SethL** [comment]
same unfortunately 
2023/02/10 14:26:53.959885 [DVR] Fetched guide data for XMLTV-SamsungTVPlus in 0s
2023/02/10 14:26:54.065000 [DVR] Indexed 0 airings into XMLTV-SamsungTVPlus (242 channels over 0s) + 1960 skipped [0s index]

**Comment by SethL** [comment]
I compared mine to https://raw.githubusercontent.com/matthuisman/i.mjh.nz/master/SamsungTVPlus/us.xml and they are identical.

**Comment by itprotj** [comment]
I'm seeing similar problems with my setup in TVH. I started to have guide data disappear a few days ago, PlutoTV data is still updating as per normal but samsungtvplus guide has stopped showing anything...
