### ISSUE TITLE
Please add the AU reigon channels

### ISSUE THREAD

**Issue by paul19920801** [matthuisman/samsung-tvplus-for-channels#9]
Pulled the good channels from Appsatv before the site went down, channels such as Smithsonian channel can only be viewed from the AU reigon of Samsung TV plus. 

I need the EPG. 

Any specific reason why this hasn't been done?

Thanks

**Comment by matthuisman** [comment]
I pull from their android app. Australia not on app. Once Australia on app, it'll be automatically added
